ToDoMvc/ToDoMvc/Models/ToDoItem.cs
using System;

namespace ToDoMvc.Models
{
    public class ToDoItem
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool Done { get; set; }
    }
}

ToDoMvc/ToDoMvc/Controllers/ToDoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Web.Mvc;
using ToDoMvc.Models;

namespace ToDoMvc.Controllers
{
    public class ToDoController : Controller
    {
        private readonly string mvcDbConnectionString = @"Server=DESKTOP-52LH9TL\SQLEXPRESS;Database=MvcVjezba;Trusted_Connection=True;";
        
        public ActionResult Index()
        {
            List<ToDoItem> itemsList = new List<ToDoItem>();
            using (SqlConnection conn = new SqlConnection(mvcDbConnectionString))
            {
                string sql = @"SELECT * FROM dbo.ToDoItem;";

                DataTable dt = new DataTable();
                SqlDataAdapter da = new SqlDataAdapter();
                da.SelectCommand = new SqlCommand(sql, conn);

                da.Fill(dt);

                foreach (DataRow row in dt.Rows)
                {
                    var item = new ToDoItem();
                    item.Id = Int32.Parse(row["Id"].ToString());
                    item.CreatedDate = Convert.ToDateTime(row["CreatedDate"]);
                    item.Description = row["Description"].ToString();
                    item.Done = Convert.ToBoolean(row["Done"]);
                    itemsList.Add(item);
                }
            }
            return View(itemsList);
        }
        
        public ActionResult AddItem(string itemDescription)
        {
            using (SqlConnection conn = new SqlConnection(mvcDbConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandType = CommandType.Text;
                    cmd.CommandText = "INSERT INTO dbo.TodoItem(Description, CreatedDate, Done) VALUES(@description, @createdDate, @done)";

                    cmd.Parameters.AddWithValue("@description", itemDescription);
                    cmd.Parameters.AddWithValue("@createdDate", DateTime.UtcNow);
                    cmd.Parameters.AddWithValue("@done", false);

                    try
                    {
                        conn.Open();
                        cmd.ExecuteNonQuery();
                        return RedirectToAction("Index");
                    }
                    catch (SqlException e)
                    {
                        return View();
                    }
                }
            }
        }

        public ActionResult DeleteItem(int itemId)
        {
            using (SqlConnection conn = new SqlConnection(mvcDbConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandType = CommandType.Text;
                    cmd.CommandText = "DELETE FROM dbo.TodoItem WHERE Id = @itemId";

                    cmd.Parameters.AddWithValue("@itemId", itemId);

                    try
                    {
                        conn.Open();
                        cmd.ExecuteNonQuery();
                        return RedirectToAction("Index");
                    }
                    catch (SqlException e)
                    {
                        return View();
                    }
                }
            }
        }

        public ActionResult SetAsDone(int itemId, bool isDone)
        {
            using (SqlConnection conn = new SqlConnection(mvcDbConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandType = CommandType.Text;
                    cmd.CommandText = "UPDATE dbo.TodoItem SET Done = @isDone WHERE Id = @itemId";

                    cmd.Parameters.AddWithValue("@isDone", !isDone);
                    cmd.Parameters.AddWithValue("@itemId", itemId);

                    try
                    {
                        conn.Open();
                        cmd.ExecuteNonQuery();
                        return RedirectToAction("Index");
                    }
                    catch (SqlException e)
                    {
                        return View();
                    }
                }
            }
        }
    }
}

ToDoMvc/ToDoMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

ToDoMvc/ToDoMvc/Views/ToDo/Index.cshtml
@model IEnumerable<ToDoMvc.Models.ToDoItem>

@{
    ViewBag.Title = "Index";
}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/base.css")
    @Styles.Render("~/Content/index.css")
    @Styles.Render("~/Content/app.css")
</head>
<body>
    <br />
    <section class="todoapp">
        <header class="header">
            <h1>todos</h1>
            @using (Html.BeginForm("AddItem", "ToDo", FormMethod.Get))
            {
                <input id="itemDescription" name="itemDescription" class="new-todo" placeholder="What needs to be done?" autofocus="">
                <input type="button" style="position: absolute; left: -9999px" />
            }

        </header>
        <section class="main" style="display: block;">
            <input id="toggle-all" class="toggle-all" type="checkbox">
            <label for="toggle-all">Mark all as complete</label>
            <ul class="todo-list">
                @foreach (var item in Model)
                {
                    <li data-id="5acee6f2-e22c-45e7-8bcd-7999aae47ddf">
                        <div class="view">
                            <input class="toggle" type="checkbox" checked=@item.Done onclick="location.href='@Url.Action("SetAsDone", "ToDo", new { itemId = @item.Id, isDone = @item.Done })'">
                            <label><input class="edit2" value=@item.Description></label>
                            <button class="destroy" onclick="location.href='@Url.Action("DeleteItem", "ToDo", new { itemId = @item.Id })'"></button>
                        </div>
                        <input class="edit" value="dsad">
                    </li>
                }
            </ul>
        </section>
    </section>
    <footer class="info">
        <p>My .net TodoMVC</a></p>
    </footer>
</body>
</html>